Added support for prerelease and nightly repos
gazebo-tooling/setup-gazebo pull request #20
Opened 2024-06-15 10:31 UTC by sauk2

Closes #17 

## Summary

This PR adds support to `ubuntu-prerelease` and `ubuntu-nightly` Gazebo repositories.

Two additional tests have been added to the workflow to test the installation of `harmonic` on `jammy` and `noble` using the unstable repos.

2024-06-16 16:26 UTC, j-rivero requested changes
Thanks for the PR!

Both prelease and nighly can be installed together, both requires to have gazebo-stable but all three can be working perfectly. Let's change the code so we can use that option.

In the PR we also need documenttion in the README about how to use these options.

2024-06-16 16:26 UTC, j-rivero commented on dist/index.js
> +            throw new Error("Cannot select Gazebo pre-release and nightly together.");
Sorry if I was not clear, both repositories can be used at the same time.

2024-06-17 17:50 UTC, sauk2 commented
> Thanks for the PR!
> 
> Both prelease and nighly can be installed together, both requires to have gazebo-stable but all three can be working perfectly. Let's change the code so we can use that option.
> 
> In the PR we also need documenttion in the README about how to use these options.

Updated the function to allow both the nightly and prerelease together. All checks pass. Will be adding tests and updating README!

2024-06-18 13:53 UTC, sauk2 commented
@j-rivero Added unit tests and updated README with instructions. All checks pass!

2024-06-18 13:54 UTC, sauk2 commented on .github/workflows/test.yml
> +          required-gazebo-distributions: 'harmonic'
Sounds like a great idea!

2024-06-18 14:24 UTC, sauk2 commented on .github/workflows/test.yml
> +          required-gazebo-distributions: 'harmonic'
Changed nightly test to install ionic

2024-06-18 14:27 UTC, j-rivero commented on .github/workflows/test.yml
> +      image: ubuntu:jammy
```suggestion
      # Ionic should be running on Noble but existing bug is releasing it into jammy
      image: ubuntu:jammy
```

2024-06-18 15:06 UTC, merged